package graphics;

// this object cycles through animation IDs at a certain interval
public class Animator implements Runnable{
	
	private static final int DEFAULT_ANIMATION_INTERVAL = 200;
	
	private int animationID, amountOfAnimations, animationInterval;
	
	public Thread thread;
	
	public Animator(int amount){
		this(amount, DEFAULT_ANIMATION_INTERVAL);
	}
	
	public Animator(int amount, int interval){
		amountOfAnimations = amount;
		animationID = 0;
		animationInterval = interval;
	}
	
	// sets the number of animations the animator will cycle through
	public void setAmountOfAnimations(int amount){
		amountOfAnimations = amount;
	}
	
	// returns an animation generated by the thread
	public int getAnimationIndex(){
		return animationID;
	}

	// switches displayed sprite
	@Override
	public void run() {
		while (!Thread.interrupted()){
			try {
				Thread.sleep(animationInterval);
				animationID++;
				if (animationID >= amountOfAnimations) animationID = 0;
			} catch (InterruptedException e) {
			}
		}
	}

}
