package graphics;

import java.awt.image.BufferedImage;

import repository.GraphicsManager;

public class Darkener implements Runnable {

	private static final int DEFAULT_ANIMATION_INTERVAL = 75;
	private static final int DEFAULT_ANIMATION_END = 750;
	
	private int animationProgression, animationID;
	
	public Thread thread;

	
	
	public Darkener() {
		animationID = -1;
		animationProgression = 0;
	}

	// returns an animation generated by the thread
	private int getAnimationIndex(){
		return animationID;
	}
	
	public void setAnimationID(int ID){
		animationID = ID;
	}
	
	public BufferedImage getDarkenedScreen(){
		switch (getAnimationIndex()){
			case 0: return GraphicsManager.darkenedScreen1;
			case 1: return GraphicsManager.darkenedScreen2;
			case 2: return GraphicsManager.darkenedScreen3;
			case 3: return GraphicsManager.darkenedScreen4;
			case 4: return GraphicsManager.darkenedScreen5;
			case 5: return GraphicsManager.darkenedScreen6;
			case 6: return GraphicsManager.darkenedScreen7;
			case 7: return GraphicsManager.darkenedScreen8;
			case 8: return GraphicsManager.darkenedScreen9;
			case 9: return GraphicsManager.darkenedScreen10;
		}
		return null;
	}
	
	@Override
	public void run() {
		while (animationProgression <= DEFAULT_ANIMATION_END){
			try {
				Thread.sleep(DEFAULT_ANIMATION_INTERVAL);
				animationID++;
				animationProgression += DEFAULT_ANIMATION_INTERVAL;
				//System.err.println(animationProgression);
			} catch (InterruptedException e) {
			}
		}
		animationID = -1;
	}

}
